---

# Any hosts

- hosts:
    - any
  become: true
  vars_files:
    - variables.yml
  tasks:
  - name: Place hosts files for internal domain resolving
    template:
      src: templates/etc/hosts
      dest: /etc/hosts

  - name: Install LXD
    apt:
      name: "{{ lxd_packages }}"
      state: latest
      default_release: xenial-backports
      update_cache: yes
    tags:
    - packages

  - name: Place preseed file
    template:
      src: templates/tmp/preseed.yml
      dest: /tmp/preseed.yml
      owner: root
      group: root
      mode: 0644
    tags:
    - preseed

  - name: Configure LXD
    command: "bash -c 'cat /tmp/preseed.yml | lxd init --preseed'"
#    args:
#      creates: /var/lib/lxcfs/cgroup/blkio/system.slice/lxd.service
    tags:
    - preseed

  - name: Configure the remotes
    script: scripts/{{ ansible_hostname }}-remote-config.sh
    tags:
    - remoteconfig

  - name: copy lxd-forward script
    copy:
      src: scripts/lxd-forward.sh
      dest: /usr/local/sbin/lxd-forward
      owner: root
      group: root
      mode: 0700
    tags:
    - forwardscript