---

# Any hosts

- hosts:
    - any
  become: true
  vars_files:
    - variables.yml
  tasks:
  - name: Place hosts files for internal domain resolving
    template:
      src: templates/etc/hosts
      dest: /etc/hosts

  - name: Install snapd packages
    apt:
      name: "{{ lxd_packages }}"
      state: latest
      update_cache: yes

  - name: Install LXD
    command: snap install lxd
    args:
      creates: /var/snap/lxd
    tags:
    - lxd
