---

# Any hosts

- hosts:
    - any
  become: true
  vars_files:
    - variables.yml
  tasks:
  - name: Place hosts files for internal domain resolving
    template:
      src: templates/etc/hosts
      dest: /etc/hosts

  - name: Install lxd packages
    apt:
      name: "{{ lxd_packages }}"
      state: latest
      default_release: xenial-backports
      update_cache: yes

  - name: Place preseed file
    template:
      src: templates/tmp/preseed.yml
      dest: /tmp/preseed.yml
      owner: root
      group: root
      mode: 0644
    tags:
      preseed